#version 430 core
layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;
layout (location = 0) uniform float boidSpeed;

struct Instance {
    vec3 pos;
    vec3 vel;
};

layout(std430, binding = 0) buffer InstanceData
{
    Instance instances[];
};


void main() {
    uint id = gl_GlobalInvocationID.x;
    Instance i = instances[id];

    i.pos += normalize(i.vel) * boidSpeed;

    instances[id] = i;
}
